### ISSUE TITLE
Reshaper startup failed

### ISSUE THREAD

**Issue by rob-ip** [synfron/ReshaperForBurp#43]
I setup ResharperForBurp on MacOS.

However, now the extension will not load when Burp launches:

`Errors` shows the following:

```
{
  "message" : "Reshaper startup failed",
  "exception" : "com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a quoted scalar\n in 'reader', line 1, column 115076:\n     ... se\"},{\"persistent\":true,\"value\":\"HTTP/2 200 OK\\r\\nContent-Type:  ... \n                                         ^\nfound unexpected end of stream\n in 'reader', line 1, column 770049:\n     ...                 category: \\\"logi\n                                         ^\n\n at [Source: (StringReader); line: 1, column: 115048]\nsynfron.reshaper.burp.core.exceptions.WrappedException: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a quoted scalar\n in 'reader', line 1, column 115076:\n     ... se\"},{\"persistent\":true,\"value\":\"HTTP/2 200 OK\\r\\nContent-Type:  ... \n                                         ^\nfound unexpected end of stream\n in 'reader', line 1, column 770049:\n     ...                 category: \\\"logi\n                                         ^\n\n at [Source: (StringReader); line: 1, column: 115048]\n\tat synfron.reshaper.burp.core.utils.Serializer.deserialize(Serializer.java:117)\n\tat synfron.reshaper.burp.core.settings.Storage.get(Storage.java:18)\n\tat synfron.reshaper.burp.core.settings.SettingsManager.loadSettings(SettingsManager.java:58)\n\tat burp.BurpExtender.initialize(BurpExtender.java:45)\n\tat burp.Zs6i.Zj(Unknown Source)\n\tat burp.Zt_.Zz(Unknown Source)\n\tat burp.Ztp.lambda$initialiseOnNewThread$0(Unknown Source)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a quoted scalar\n in 'reader', line 1, column 115076:\n     ... se\"},{\"persistent\":true,\"value\":\"HTTP/2 200 OK\\r\\nContent-Type:  ... \n                                         ^\nfound unexpected end of stream\n in 'reader', line 1, column 770049:\n     ...                 category: \\\"logi\n                                         ^\n\n at [Source: (StringReader); line: 1, column: 115048]\n\tat com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:28)\n\tat com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:423)\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:350)\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)\n\tat com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)\n\tat com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)\n\tat com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)\n\tat com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)\n\tat synfron.reshaper.burp.core.utils.Serializer.deserialize(Serializer.java:115)\n\t... 11 more\nCaused by: while scanning a quoted scalar\n in 'reader', line 1, column 115076:\n     ... se\"},{\"persistent\":true,\"value\":\"HTTP/2 200 OK\\r\\nContent-Type:  ... \n                                         ^\nfound unexpected end of stream\n in 'reader', line 1, column 770049:\n     ...                 category: \\\"logi\n                                         ^\n\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1991)\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1904)\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1082)\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1064)\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:452)\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263)\n\tat org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:790)\n\tat org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185)\n\tat org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:195)\n\tat com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:419)\n\t... 19 more\n"
}
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a quoted scalar
 in 'reader', line 1, column 115076:
     ... se"},{"persistent":true,"value":"HTTP/2 200 OK\r\nContent-Type:  ... 
                                         ^
found unexpected end of stream
 in 'reader', line 1, column 770049:
     ...                 category: \"logi
                                         ^

 at [Source: (StringReader); line: 1, column: 115048]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:28)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:423)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:350)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)
	at synfron.reshaper.burp.core.utils.Serializer.deserialize(Serializer.java:115)
	at synfron.reshaper.burp.core.settings.Storage.get(Storage.java:18)
	at synfron.reshaper.burp.core.settings.SettingsManager.loadSettings(SettingsManager.java:58)
	at burp.BurpExtender.initialize(BurpExtender.java:45)
	at burp.Zs6i.Zj(Unknown Source)
	at burp.Zt_.Zz(Unknown Source)
	at burp.Ztp.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: while scanning a quoted scalar
 in 'reader', line 1, column 115076:
     ... se"},{"persistent":true,"value":"HTTP/2 200 OK\r\nContent-Type:  ... 
                                         ^
found unexpected end of stream
 in 'reader', line 1, column 770049:
     ...                 category: \"logi
                                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1991)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1904)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1082)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1064)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:452)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:790)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:195)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:419)
	... 19 more
```

Where is this config actually saved? If I could workaround by deleting it, I could try importing my settings again.

**Comment by ddwightx** [comment]
Reshaper's data is stored as preferences in Burp which ultimately uses the Java Preferences library to store the data. Note, if you do not have a backup of the Reshaper's exportable data, you may want to have a copy of the data in the below locations before deleting them for later inspection. 

Not sure if there is a Java Preferences viewer/editor available somewhere that allows an easy interface for fixing the JSON or deleting. If not, you can follow the below.


On Windows, Java Preferences for Reshaper are stored in the Registry at `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\burp\extensions\_/Reshaper`. Deleting that key basically resets Reshaper (tested and confirmed). 

On the Mac, they are stored in `~/Library/Preferences/burp.extensions._reshaper.plist`. If you view it, you might be able to spot the error in the JSON and fix it directly. Otherwise, deleting this file entirely I expect would reset Reshaper (have not tested).

Is there a particular set of actions that you did that you believe may have caused the issue? Based on the error, I wonder if somehow the full JSON wasn't stored in the preferences (maybe system size limit reached?) and caused the issue? I notice in the error message you showed, there is a HTTP response being persisted as a global variable. Is it rather large or do you have many that together may be large? If so, consider storing the HTTP responses in a file and access it via the [File variable tag](https://synfron.github.io/ReshaperForBurp/Variables.html#variable-tags) and update the file using the Then Save File as needed.

**Comment by ddwightx** [comment]
Ah, that's failing because nested variable tags are not supported. 
So, instead you'll need to do a hybrid approach. You can still store the files locally, but you'll have to read them into a global or event variable. This doesn't cause the same concern as your original issue though as long as you don't choose to persist the variable.

To retrieve a file into a variable where the file path is dynamic, you can use Then Run Process:

Command - ` cat {{event:path}}`
Wait for Completion - `Checked`
Capture Output - `Checked`
Capture Variable - Your choice
Capture Variable Name - Your choice
