### ISSUE TITLE
WebSocket Rules "In Scope" - Exceptions

### ISSUE THREAD

**Issue by rob-ip** [synfron/ReshaperForBurp#46]
[Your documentation](https://synfron.github.io/ReshaperForBurp/Rules.html#whens) states

> In Scope
If the URL is in the suite-wide scope
>
> Availability: HTTP, WebSocket
>
> Fields
URL - The URL to check or leave blank to use the current request’s URL. Supports variable tags.

However, if I use this `Then` with a blank URL in a WebSocket Rule I get exceptions under `Extensions > Installed > Reshaper > Errors`

```
java.lang.IllegalArgumentException: Invalid URL
	at burp.Znlv.isInScope(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zaa5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy94.isInScope(Unknown Source)
	at burp.Ztoe.isInScope(Unknown Source)
	at synfron.reshaper.burp.core.rules.whens.WhenInScope.isMatch(WhenInScope.java:24)
	at synfron.reshaper.burp.core.rules.whens.IWhenGroup.isMatch(IWhenGroup.java:39)
	at synfron.reshaper.burp.core.rules.whens.IWhenGroup.isMatch(IWhenGroup.java:25)
	at synfron.reshaper.burp.core.rules.RulesEngine.run(RulesEngine.java:45)
	at synfron.reshaper.burp.core.rules.RulesEngine.run(RulesEngine.java:21)
	at synfron.reshaper.burp.core.WebSocketConnector$WebSocketMessageConnector.processEvent(WebSocketConnector.java:117)
	at synfron.reshaper.burp.core.WebSocketConnector$WebSocketMessageConnector.handleBinaryMessageReceived(WebSocketConnector.java:91)
	at burp.Zhxr.ZO(Unknown Source)
	at burp.Zi_m.ZJ(Unknown Source)
	at burp.Zit9.ZD(Unknown Source)
	at net.portswigger.Zfk.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

and the rule doesn't work. Please advise, thanks in advance.

**Comment by ddwightx** [comment]
Ah, it appears as though [Burp's Montoya API](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/scope/Scope.html#isInScope(java.lang.String)) does not support checking that a WebSocket URL is in scope. WebSocket URLs contain wss:// or ws://, but Burp seems to only allow HTTP URLs. I will have to update the documentation to note that the URL must be HTTP based and if under WebSocket Rules, the URL must be specified.

**Comment by ddwightx** [comment]
Will update the UI to require a URL to be specified for this constraint under WebSockets. Fix targeted for next release, tracked in https://github.com/synfron/ReshaperForBurp/issues/50.

**Comment by ddwightx** [comment]
@rob-ip If you want, feel free to test if this pre-release addresses your issue. https://github.com/synfron/ReshaperForBurp/releases/tag/v2.3.0-pre
